# Generated by Django 6.0.3 on 2026-03-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_department'),
        ('users', '0002_user_branch_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='managers', to='branches.department', verbose_name='Отделы менеджера'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('manager', 'Менеджер отдела'), ('service_admin', 'Администратор сервиса'), ('main_admin', 'Главный администратор')], default='user', max_length=20, verbose_name='Роль пользователя'),
        ),
    ]
