# Generated by Django 5.2.12 on 2026-03-06 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Специализация')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('is_active', models.BooleanField(default=True, help_text='Уберите галочку, если мастер уволен или в долгом отпуске', verbose_name='Работает в данный момент')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanics', to='branches.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость (руб.)')),
                ('duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Примерная длительность (в минутах)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Услуга активна')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='branches.branch', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
                'unique_together': {('branch', 'name')},
            },
        ),
    ]
