# Generated by Django 6.0.3 on 2026-03-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_alter_branch_id_alter_department_id_and_more'),
        ('services', '0006_alter_mechanic_id_alter_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanic',
            name='specialization',
        ),
        migrations.AddField(
            model_name='mechanic',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='mechanics', to='branches.department'),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
