# Generated by Django 5.2.12 on 2026-03-06 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название филиала')),
                ('address', models.CharField(max_length=255, verbose_name='Физический адрес')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Контактный телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Филиал работает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='branches.branch', verbose_name='Управляемый филиал')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (Админ)')),
            ],
            options={
                'verbose_name': 'Профиль администратора филиала',
                'verbose_name_plural': 'Профили администраторов филиалов',
            },
        ),
    ]
