# Generated by Django 6.0.3 on 2026-03-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна в филиале'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название категории'),
        ),
    ]
