# Generated by Django 6.0.3 on 2026-03-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_alter_branch_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бокса/поста')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='branches.branch', verbose_name='Филиал')),
                ('departments', models.ManyToManyField(blank=True, related_name='boxes', to='branches.department', verbose_name='Отделы (для которых подходит бокс)')),
            ],
            options={
                'verbose_name': 'Бокс / Пост',
                'verbose_name_plural': 'Боксы / Посты',
            },
        ),
    ]
