# Generated by Django 5.2.12 on 2026-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0012_alter_box_id_alter_branch_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='icon',
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/icons/', verbose_name='Иконка отдела'),
        ),
    ]
