# Generated by Django 5.2.12 on 2026-03-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0013_remove_department_icon_department_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='image',
        ),
    ]
