# Generated by Django 5.2.12 on 2026-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0014_remove_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Контактный телефон 2'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Контактный телефон 1'),
        ),
    ]
