# Generated by Django 5.2.12 on 2026-04-08 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0015_branch_phone_number_2_alter_branch_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='closing_time',
            field=models.TimeField(default=datetime.time(20, 0), verbose_name='Время закрытия'),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Время открытия'),
        ),
    ]
