# Generated by Django 5.2.12 on 2026-03-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_brand',
            field=models.CharField(default='Не указана', max_length=100, verbose_name='Марка авто'),
        ),
        migrations.AddField(
            model_name='order',
            name='car_model',
            field=models.CharField(default='Не указана', max_length=100, verbose_name='Модель авто'),
        ),
        migrations.AddField(
            model_name='order',
            name='car_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждена'), ('in_progress', 'В работе'), ('completed', 'Выполнено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
