# Generated by Django 6.0.3 on 2026-03-11 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0009_box'),
        ('orders', '0008_alter_order_id'),
        ('services', '0007_remove_mechanic_specialization_mechanic_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.box'),
        ),
        migrations.AddField(
            model_name='order',
            name='duration_minutes',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.mechanic'),
        ),
    ]
