# Generated by Django 6.0.3 on 2026-03-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car_vin',
            field=models.CharField(blank=True, max_length=17, verbose_name='VIN-код'),
        ),
        migrations.AlterField(
            model_name='order',
            name='car_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Гос. номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
