# Generated by Django 5.2.12 on 2026-04-08 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_linked',
            field=models.BooleanField(default=False, verbose_name='Привязан к аккаунту'),
        ),
        migrations.AddField(
            model_name='order',
            name='linking_pin',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='PIN для привязки'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон клиента (если нет аккаунта)'),
        ),
        migrations.AddField(
            model_name='order',
            name='pin_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия PIN'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
